/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package numberconverter;

import java.math.BigInteger;

public final class Number {
  private Words words;
  private BigInteger number;
  private Standard standard;

  public Number(byte number) {
    this(new BigInteger(String.valueOf(number)));
  }

  public Number(short number) {
    this(new BigInteger(String.valueOf(number)));
  }

  public Number(int number) {
    this(new BigInteger(String.valueOf(number)));
  }

  public Number(long number) {
    this(new BigInteger(String.valueOf(number)));
  }

  public Number(BigInteger number) {
    this.number = number;
    this.standard = Standard.INTERNATIONAL;
  }

  public Number(byte number, Standard standard) {
    this(new BigInteger(String.valueOf(number)), standard);
  }

  public Number(short number, Standard standard) {
    this(new BigInteger(String.valueOf(number)), standard);
  }

  public Number(int number, Standard standard) {
    this(new BigInteger(String.valueOf(number)), standard);
  }

  public Number(long number, Standard standard) {
    this(new BigInteger(String.valueOf(number)), standard);
  }

  public Number(BigInteger number, Standard standard) {
    this.number = number;
    this.standard = Standard.INTERNATIONAL;
  }

  private static Words belowNine(BigInteger num) {
    return Words.values()[num.intValue()];
  }

  //TODO
  public String getWords() {
    return "";
  }
  
  public static void main(String[] args) {
    System.out.println(Number.belowNine(new BigInteger("2")));
    System.out.println(Number.belowNine(new BigInteger("9")));
  }
}
