/*
 * This Java source file was generated by the Gradle 'init' task. 
 */
package numberconverter;

public final class Number {
  private Words words;
  private long number;
  private Standard standard;

  public Number(long number) {
    this(number, Standard.INTERNATIONAL);
  }

  public Number(long number, Standard standard) {
    if (number < 0) {
      throw new NegativeNumberException();
    }
    this.number = number;
    this.standard = standard;
  }

  private static String belowNine(long num) {
    return Words.values()[(int) num].toString();
  }

  public String getWords() {
    long tempNumber = this.number;
    if (tempNumber < 10) {
      return belowNine(tempNumber);
    }
    return "";
  }

  public static void main(String[] args) {
    System.out.println(Number.belowNine(2));
    System.out.println(Number.belowNine(9));
  }
}

